cartpole1:
  env_id: CartPole-v1
  replay_memory_size: 100000
  batch_size: 32
  epsilon_init: 1
  epsilon_min: 0.05
  epsilon_decay: 0.9995
  sync_rate: 10
  learning_rate: 0.0001
  discount_factor: 0.99

mountain_car1:
  env_id: MountainCar-v0
  replay_memory_size: 100000
  batch_size: 32
  epsilon_init: 1
  epsilon_min: 0.05
  epsilon_decay: 0.9995
  sync_rate: 10
  learning_rate: 0.0001
  discount_factor: 0.99
  
pendulum1:
  env_id: Pendulum-v0
  replay_memory_size: 100000
  batch_size: 64
  epsilon_init: 1
  epsilon_min: 0.05
  epsilon_decay: 0.95